USE [master]
GO

/****** Object:  Database [libraryDB]    Script Date: 12/16/2019 9:03:59 AM ******/
CREATE DATABASE [libraryDB]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'libraryDB', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\libraryDB.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'libraryDB_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\libraryDB_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [libraryDB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [libraryDB] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [libraryDB] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [libraryDB] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [libraryDB] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [libraryDB] SET ARITHABORT OFF 
GO

ALTER DATABASE [libraryDB] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [libraryDB] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [libraryDB] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [libraryDB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [libraryDB] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [libraryDB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [libraryDB] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [libraryDB] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [libraryDB] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [libraryDB] SET  DISABLE_BROKER 
GO

ALTER DATABASE [libraryDB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [libraryDB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [libraryDB] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [libraryDB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [libraryDB] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [libraryDB] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [libraryDB] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [libraryDB] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [libraryDB] SET  MULTI_USER 
GO

ALTER DATABASE [libraryDB] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [libraryDB] SET DB_CHAINING OFF 
GO

ALTER DATABASE [libraryDB] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [libraryDB] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [libraryDB] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [libraryDB] SET QUERY_STORE = OFF
GO

ALTER DATABASE [libraryDB] SET  READ_WRITE 
GO

